-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Waktu pembuatan: 28 Bulan Mei 2024 pada 07.35
-- Versi server: 10.4.27-MariaDB
-- Versi PHP: 8.1.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `boole_db`
--

-- --------------------------------------------------------

--
-- Struktur dari tabel `destination`
--

CREATE TABLE `destination` (
  `id` int(11) NOT NULL,
  `place` varchar(30) NOT NULL,
  `category` varchar(15) NOT NULL,
  `description` text NOT NULL,
  `address` varchar(255) NOT NULL,
  `picture` varchar(50) NOT NULL,
  `link_maps` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data untuk tabel `destination`
--

INSERT INTO `destination` (`id`, `place`, `category`, `description`, `address`, `picture`, `link_maps`) VALUES
(1, 'Wohkudu Beach', 'Beach', 'Wohkudu Beach, a secluded paradise along the untouched coastline, mesmerizes with its unspoiled beauty and serene ambiance. The expansive stretch of golden sands, delicately kissed by the sun, extends as far as the eye can see, creating a picturesque landscape against the backdrop of the clear azure sky. The rhythmic melody of gentle waves caressing the shore adds to the tranquil atmosphere, making Wohkudu a haven for relaxation and reflection.\r\n\r\nNestled in nature\'s embrace, Wohkudu remains relatively undiscovered, preserving its authenticity and providing a genuine escape from the frenetic pace of modern life. The beach is a sanctuary where visitors can immerse themselves in the soothing sounds of the sea, take leisurely walks along the shoreline, and appreciate the simplicity of the surroundings.\r\n\r\nWith minimal development, Wohkudu retains its natural charm, offering a pure and unspoiled coastal experience. The beach is an ideal destination for those seeking solitude, where the only distractions are the rustling leaves and the distant calls of seabirds. Wohkudu Beach invites travelers to disconnect from the outside world, rejuvenate in the lap of nature, and witness the timeless beauty of an untouched coastal masterpiece.', 'Gunung Kidul, Special Region of Yogyakarta', 'wohkudu.jpg', 'https://maps.app.goo.gl/AdMjy8MEjYjhFvuQ7'),
(2, 'Ngobaran Beach', 'Beach', 'Ngobaran Beach, an enchanting coastal haven, beckons with its unique blend of natural beauty and cultural richness. The powdery white sands stretch gracefully along the shoreline, meeting the crystal-clear waters of the Indian Ocean. What sets Ngobaran apart is its deep cultural significance, seamlessly intertwined with the coastal landscape. Ancient temples, including the Segara Kidul and the sacred Perawan Cave, add a spiritual dimension to the beach.\r\n\r\nVisitors to Ngobaran have the opportunity to immerse themselves in local traditions, witnessing traditional ceremonies and rituals that take place on the beach. The rhythmic sounds of waves harmonize with the spiritual ambiance, creating a truly unique experience.\r\n\r\nBeyond its cultural allure, Ngobaran offers a serene escape for beach enthusiasts. The tranquil atmosphere invites visitors to relax on the soft sands, basking in the warmth of the sun. The beach\'s scenic beauty, coupled with its cultural depth, makes Ngobaran a multifaceted destination, appealing to those seeking both a tranquil retreat and a cultural exploration along the mesmerizing coastline.', 'Gunung Kidul, Special Region of Yogyakarta', 'ngobaran.jpg', 'https://maps.app.goo.gl/vziFwkcpKN3gd2AD7'),
(3, 'Indrayanti beach', 'Beach', 'Indrayanti Beach, a coastal jewel on the southern shores of Java, captivates with its breathtaking beauty and vibrant atmosphere. The beach unveils a postcard-perfect scene, where pristine white sands meet the mesmerizing turquoise waters of the Indian Ocean. Lined with swaying palm trees, Indrayanti exudes a tropical paradise ambiance, inviting visitors to indulge in the sheer splendor of nature.\r\n\r\nWhat sets Indrayanti apart is its lively beachfront scene. Quaint beach cafes, adorned with colorful umbrellas, offer a delightful setting to savor local cuisine while enjoying panoramic views of the ocean. The beach comes alive with the laughter of beachgoers, creating a cheerful and welcoming atmosphere.\r\n\r\nSun worshippers find bliss on the golden sands, and the clear waters invite swimmers and snorkelers to explore the vibrant underwater world. As the sun sets, Indrayanti transforms into a magical panorama, with the sky ablaze in hues of orange and pink, casting a warm glow over the coastal landscape.\r\n\r\nIndrayanti Beach seamlessly combines natural allure with a lively beach culture, making it a must-visit destination for those seeking a perfect blend of relaxation and vibrant coastal energy along the enchanting southern coast of Java.', 'Gunung Kidul, Special Region of Yogyakarta', 'indrayanti.jpg', 'https://maps.app.goo.gl/pedPCGk8vp17TUJW6'),
(4, 'Parangtritis Beach', 'Beach', 'Parangtritis Beach, situated along the southern coast of Java, is a captivating blend of natural grandeur and cultural mystique. The expansive sandy shores, adorned with fine golden sands, stretch as far as the eye can see, meeting the roaring waves of the Indian Ocean. The beach\'s dramatic landscape, marked by vast sand dunes, creates a picturesque panorama against the azure sky.\r\n\r\nBeyond its scenic beauty, Parangtritis holds profound cultural significance. Legend has it that the beach is guarded by the mystical Queen of the South Sea, adding an air of enchantment to the surroundings. Visitors can embark on horse-drawn carriage rides along the shore, offering a unique and traditional way to explore the coastal landscape.\r\n\r\nAs the sun sets, Parangtritis transforms into a magical realm, with the vibrant hues reflecting off the ocean waves and creating a breathtaking spectacle. The beach is not only a visual delight but also a place where visitors can immerse themselves in the rich cultural heritage and folklore of the region.\r\n\r\nParangtritis Beach stands as a multifaceted destination, appealing to both nature lovers and those seeking a cultural exploration along the captivating southern coast of Java.', 'Gunung Kidul, Special Region of Yogyakarta', 'parangtritis.jpg', 'https://maps.app.goo.gl/cF3jHnXdSGsCqMaK9'),
(5, 'Nglambor Beach', 'Beach', 'Nglambor Beach, a hidden gem on the southern coast of Java, unveils a pristine coastal paradise that combines untouched natural beauty with tranquility. The beach is characterized by its powdery white sands that gently meet the clear, turquoise waters of the Indian Ocean, creating a serene and inviting atmosphere. Nestled amidst lush greenery, Nglambor retains a sense of seclusion, making it an ideal escape from the hustle and bustle of everyday life.\r\n\r\nThe secluded nature of Nglambor makes it a haven for those seeking a peaceful retreat. The calm waters offer opportunities for swimming and snorkeling, allowing visitors to explore the vibrant marine life beneath the surface. The beach\'s unspoiled surroundings and relatively untouched landscape contribute to its allure, providing a genuine connection with nature.\r\n\r\nNglambor is not only a visual feast but also a sanctuary where the soothing sounds of waves harmonize with the rustling leaves, creating a symphony of tranquility. Whether one is seeking relaxation under the sun or an exploration of the coastal ecosystem, Nglambor Beach stands as an enchanting destination for those yearning for a serene coastal escape.', 'Gunung Kidul, Special Region of Yogyakarta', 'nglambor.jpg', 'https://maps.app.goo.gl/Uz4eFCXEfhq5quWP6'),
(6, 'Baron Beach', 'Beach', 'Baron Beach, nestled along the southern coast of Java, is a captivating blend of rugged beauty and serene coastal charm. The beach boasts a unique landscape where soft sandy stretches harmoniously coexist with dramatic cliffs, creating a picturesque panorama. The golden sands invite visitors to unwind and take leisurely walks, while the rugged cliffs provide a stunning backdrop that sets Baron apart from other coastal destinations.\r\n\r\nWhat makes Baron truly special is its topography, where nature\'s contrasts meet seamlessly. The juxtaposition of smooth sandy shores against the imposing cliffs adds an element of mystery and grandeur to the scenery. Visitors can explore the beachfront caves, adding a touch of adventure to their coastal experience.\r\n\r\nBaron is not just a visual delight; it also offers a range of activities, from beachcombing and sunbathing to exploring the nearby freshwater lagoon. The beach is known for its vibrant local atmosphere, with traditional fisherman boats dotting the shoreline.\r\n\r\nAs the sun sets over the horizon, Baron transforms into a magical realm, with the cliffs casting long shadows and the sky ablaze in warm hues. Baron Beach is an exquisite destination for those seeking both natural beauty and a touch of coastal adventure along the captivating southern coast of Java.', 'Gunung Kidul, Special Region of Yogyakarta', 'baron.jpg', 'https://maps.app.goo.gl/DsiGyddedML2naCo6'),
(7, 'Sadranan Beach', 'Beach', 'Sadranan Beach, nestled along the southern coast of Java, is a hidden retreat that unfolds as a picturesque haven of tranquility and natural beauty. The beach, with its soft golden sands, stretches gracefully along the shoreline, inviting visitors to indulge in moments of serenity. The azure waters gently caress the beach, creating a soothing ambiance that resonates with relaxation.\r\n\r\nWhat sets Sadranan apart is its tranquil atmosphere, offering a peaceful escape from the hustle and bustle of urban life. The beach remains relatively undiscovered, providing an intimate setting for those seeking solitude. Tall coconut trees line the coast, providing shade and adding to the tropical allure of the surroundings.\r\n\r\nSadranan is a paradise for sunbathers and beach enthusiasts who wish to unwind against the backdrop of a pristine coastal landscape. The gentle waves offer a refreshing retreat, making it an ideal spot for swimming or leisurely dips in the sea. \r\n\r\nAs the sun sets, Sadranan transforms into a canvas of warm hues, creating a magical ambiance that enhances the beach\'s natural charm.\r\n\r\nWith its untouched beauty and tranquil aura, Sadranan Beach stands as a serene sanctuary for nature lovers, offering an escape to a coastal paradise that invites visitors to embrace the simplicity and peacefulness of the southern Java shoreline.', 'Gunung Kidul, Special Region of Yogyakarta', 'sadranan.jpg', 'https://maps.app.goo.gl/QHiDJUjDTkD5d4fU8'),
(8, 'Pok Tunggal Beach', 'Beach', 'Pok Tunggal Beach, located along the southern coast of Java, is a coastal masterpiece that enchants visitors with its unique charm and natural elegance. The beach is renowned for its iconic rock formation, a sculpted monolith that stands proudly against the backdrop of the expansive golden sands. The crystalline waters of the Indian Ocean gently caress the shore, creating a serene and inviting ambiance.\r\n\r\nAs the sun graces the horizon, Pok Tunggal transforms into a haven for sun worshippers. The soft sands offer a perfect spot for beachgoers to bask in the warmth of the tropical sun. The impressive rock formation adds a touch of drama to the coastal landscape, making it a favorite among photographers and nature enthusiasts.\r\n\r\nPok Tunggal is not only a visual delight but also a destination for exploration. The clear waters beckon swimmers, while the rocky outcrop provides a unique backdrop for leisurely strolls. The beach\'s unspoiled beauty, coupled with its distinctive rock formation, makes Pok Tunggal a must-visit destination for those seeking a perfect blend of natural splendor and coastal tranquility along the enchanting southern coast of Java.', 'Gunung Kidul, Special Region of Yogyakarta', 'poktunggal.jpg', 'https://maps.app.goo.gl/h74SaXyyYNFDBmjV7'),
(9, 'Drini Beach', 'Beach', 'Drini Beach, nestled along the southern coast of Java, is a coastal haven that harmoniously combines sandy serenity with dramatic rock formations. The beach welcomes visitors with its fine golden sands that stretch lazily along the shoreline, inviting leisurely strolls and relaxation under the tropical sun. What sets Drini apart is the juxtaposition of its soft sands against the rugged beauty of weathered rocks and cliffs, creating a captivating and unique coastal landscape.\r\n\r\nAs waves gently lap against the shore, visitors can explore the rocky outcrops, adding an adventurous dimension to their seaside experience. Drini is a picture-perfect destination, offering panoramic views of the vast Indian Ocean and the surrounding coastal cliffs.\r\n\r\nThe beach retains a tranquil atmosphere, making it an ideal retreat for those seeking both relaxation and exploration. Whether one chooses to bask in the sun, explore the rocky nooks, or simply listen to the rhythmic sounds of the waves, Drini Beach stands as a captivating destination, where nature\'s beauty unfolds in a serene and picturesque setting along the enchanting southern coast of Java.', 'Gunung Kidul, Special Region of Yogyakarta', 'drini.jpg', 'https://maps.app.goo.gl/va6h2xs5EyJHncCM7'),
(10, 'Wediombo Beach', 'Beach', 'Wediombo Beach, nestled along the southern coast of Java, is a coastal haven that unveils a harmonious blend of natural beauty and serenity. The beach presents an expansive canvas of soft golden sands stretching gracefully along the shoreline, inviting visitors to indulge in the simple pleasure of barefoot strolls by the sea. The calm, clear waters of the Indian Ocean gently kiss the beach, creating a tranquil atmosphere that resonates with peace and relaxation.\r\n\r\nWhat sets Wediombo apart is its relatively unexplored and pristine nature, offering a secluded escape for those seeking a quiet retreat. The beach is embraced by rugged cliffs and verdant hills, providing a picturesque backdrop to the coastal landscape. Visitors can revel in the untouched beauty, whether by taking a leisurely swim, basking in the sun, or simply admiring the panoramic views.\r\n\r\nWediombo is not just a beach; it\'s a sanctuary where the soothing sounds of waves blend with the whispers of the wind through the coastal foliage. As the sun sets, the beach transforms into a canvas of warm hues, offering a breathtaking spectacle to those fortunate enough to witness the beauty of day\'s end. Wediombo Beach stands as a serene escape, inviting travelers to immerse themselves in the unspoiled charm of the southern Java coastline.', 'Gunung Kidul, Special Region of Yogyakarta', 'wediombo.jpg', 'https://maps.app.goo.gl/8zUmiZJ85twNPKFu5'),
(11, 'Siung Beach', 'Beach', 'Siung Beach, nestled along the southern coast of Java, is a dramatic coastal spectacle that seamlessly blends rugged cliffs with pristine shores. Towering limestone cliffs, adorned with lush greenery, create a stunning backdrop against the golden sands and the azure expanse of the Indian Ocean. The beach\'s unique topography makes it a haven for adventure seekers and nature enthusiasts alike.\r\n\r\nSiung is renowned for its challenging rock climbing routes, attracting climbers from around the world. The cliffs offer not only an adrenaline-pumping experience but also panoramic views of the coastline, rewarding those who ascend with breathtaking vistas. The beach also provides hiking opportunities, allowing visitors to explore the coastal trails and discover hidden gems along the way.\r\n\r\nBeyond its adventurous spirit, Siung is a serene retreat where the crashing waves against the cliffs create a rhythmic soundtrack. Sunsets at Siung are a mesmerizing spectacle, painting the sky in hues of orange and pink. The beach, with its rugged charm and natural beauty, stands as a testament to the diverse landscapes found along the southern coast of Java, inviting exploration, adventure, and appreciation for the wonders of coastal nature.', 'Gunung Kidul, Special Region of Yogyakarta', 'siung.jpg', 'https://maps.app.goo.gl/TNoy1V1C4xxfPEjh9'),
(12, 'Sepanjang Beach', 'Beach', 'Sepanjang Beach, nestled along the southern coast of Java, is a captivating stretch of pristine shoreline that unfolds like a natural tapestry of tranquility. The expansive beach boasts fine, golden sands that stretch uninterrupted, inviting visitors to take leisurely strolls against the backdrop of the azure sky. What sets Sepanjang apart is its simplicity and unspoiled beauty, offering a serene retreat away from the bustling pace of urban life.\r\n\r\nThe rhythmic sounds of gentle waves create a soothing melody, providing a calming ambiance for beachgoers. Sepanjang is an ideal destination for those seeking solitude and relaxation, where the only distractions are the whispers of the sea breeze and the distant calls of seabirds.\r\n\r\nThe clear horizon over the Indian Ocean beckons contemplation and reflection, making Sepanjang a perfect spot for quiet introspection. As the sun sets, painting the sky in warm hues, the beach transforms into a magical panorama, offering a breathtaking spectacle for those fortunate enough to witness it.\r\n\r\nSepanjang Beach, with its simplicity and natural charm, stands as a haven for nature enthusiasts and seekers of coastal serenity, providing a timeless escape along the enchanting southern coast of Java.', 'Gunung Kidul, Special Region of Yogyakarta', 'wediombo.jpg', 'https://maps.app.goo.gl/42cz9JKT4aSgV1CZA'),
(13, 'Gudeg Yu Djum', 'Culinary', 'Gudeg Yu Djum is a culinary delight hailing from Yogyakarta, Indonesia, renowned for its rich flavors and cultural significance. This traditional Javanese dish is centered around young jackfruit, slow-cooked in coconut milk and a blend of spices until it reaches a tender and succulent consistency. The result is a sweet and savory masterpiece that captures the essence of Javanese cuisine.\r\n\r\nGudeg Yu Djum is typically served with a medley of accompanying dishes, including chicken, hard-boiled eggs, tofu, and krecek (spiced beef skin). The combination of these elements creates a harmonious flavor profile that reflects the culinary diversity of the region. The dish is often enjoyed with steamed rice, enhancing the overall experience.\r\n\r\nWhat sets Gudeg Yu Djum apart is its commitment to preserving the authenticity of the recipe, passed down through generations. The slow-cooking process allows the flavors to meld, creating a dish that not only satisfies the taste buds but also tells a story of Javanese heritage.\r\n\r\nFor food enthusiasts and those eager to explore Indonesia\'s culinary treasures, Gudeg Yu Djum offers a delectable journey into the heart of Yogyakartan gastronomy, celebrating the cultural richness and flavors that define this beloved dish.', 'Sleman, Special Region of Yogyakarta', 'gudegyj.jpg', 'https://maps.app.goo.gl/x3RGfso22yVF6uvX7'),
(14, 'Bakpia Kukus Tugu Jogja', 'Culinary', 'Bakpia Kukus Tugu Jogja is a delectable culinary delight that hails from the cultural heart of Indonesia, Yogyakarta. This steamed pastry, locally known as \"bakpia kukus,\" has become an iconic treat for locals and visitors alike. Each bite offers a delightful blend of flavors and textures, making it a must-try in the vibrant culinary scene of Jogja.\r\n\r\nCrafted with precision and passion, Bakpia Kukus Tugu Jogja features a soft, steamed outer layer that encases a sweet filling. The fillings vary, from mung bean to chocolate, cheese, or even fruit flavors, providing a diverse range of taste experiences. The pastries are typically small and round, making them a perfect snack to enjoy with a cup of local tea or coffee.\r\n\r\nWhat sets Bakpia Kukus Tugu Jogja apart is not just its exquisite taste but also the cultural significance it carries. Tugu, a historical landmark in Yogyakarta, adds a touch of tradition and authenticity to this culinary masterpiece. Locals and tourists alike flock to Tugu Jogja to savor these delectable treats, creating a delightful culinary journey that encapsulates the rich flavors and cultural heritage of Yogyakarta.', 'Yogyakarta, Special Region of Yogyakarta', 'bakpiatugu.jpg', 'https://maps.app.goo.gl/CPh3gQxowyBV3oGs5'),
(15, 'Kopi Klothok', 'Culinary', 'Kopi Klothok, a culinary delight originating from Indonesia, is a unique coffee experience that tantalizes the taste buds with its distinct flavors and cultural significance. This traditional coffee is meticulously crafted, embodying the rich coffee culture of the archipelago.\r\n\r\nKopi Klothok is prepared using a traditional method where the coffee beans are roasted with a blend of spices, typically including cloves and cinnamon. This process imparts a robust and aromatic quality to the coffee, creating a brew that is both bold and nuanced. The resulting beverage offers a harmonious balance of earthy tones and a hint of spiciness, providing a sensory journey for coffee enthusiasts.\r\n\r\nBeyond its flavor profile, Kopi Klothok carries a cultural narrative. It reflects the deep-rooted coffee traditions of Indonesia, where coffee is more than just a beverage—it is a social and cultural experience. Sipping on a cup of Kopi Klothok is an invitation to partake in the rich tapestry of Indonesian coffee culture, fostering connections and conversations.\r\nWhether enjoyed in the bustling streets of Jakarta or the serene landscapes of Java, Kopi Klothok stands as a testament to the diversity and richness of Indonesian culinary heritage, inviting locals and travelers alike to savor the essence of Indonesian coffee craftsmanship.', 'Sleman, Special Region of Yogyakarta', 'kopiklotok.jpg', 'https://maps.app.goo.gl/yYfaaDVt14zggNbx7'),
(16, 'House of Raminten', 'Culinary', 'House of Raminten, located in Yogyakarta, Indonesia, is a culinary haven that seamlessly blends traditional Javanese flavors with a unique and eclectic ambiance. Stepping into this culinary gem feels like entering a cultural oasis, where rich heritage and contemporary aesthetics converge.\r\n\r\nThe menu at House of Raminten showcases a diverse array of Javanese culinary delights, ranging from traditional dishes to modern interpretations. Guests are treated to an immersive experience of flavors, with each dish telling a story of the region\'s culinary heritage. Signature offerings include Gudeg, a slow-cooked young jackfruit stew, and Ayam Panggang Klaten, grilled chicken with a flavorful blend of spices.\r\n\r\nBeyond the exquisite cuisine, the restaurant\'s décor is a visual delight. Traditional Javanese elements, vibrant batik patterns, and antique artifacts adorn the space, creating an atmosphere that resonates with authenticity. The attentive and friendly staff further enhance the dining experience, providing a warm and welcoming environment for guests.\r\n\r\nHouse of Raminten is not just a restaurant; it is a cultural journey through Javanese culinary traditions. Whether one seeks to savor authentic flavors, explore diverse dishes, or simply bask in the cultural richness of Yogyakarta, House of Raminten stands as a culinary destination that captures the essence of Javanese heritage with a contemporary twist.', 'Yogyakarta, Special Region of Yogyakarta', 'raminten.jpeg', 'https://maps.app.goo.gl/DoQesyBf9PmRMnHe9'),
(17, 'Mangut Lele Mbah Marto', 'Culinary', 'Mangut Lele Mbah Marto is a delectable culinary delight hailing from the heart of Javanese cuisine. This dish features catfish, locally known as \"lele,\" cooked to perfection in a rich and aromatic coconut-based sauce. The secret lies in the meticulous blend of traditional spices, including turmeric, ginger, shallots, garlic, and a medley of fragrant herbs.\r\n\r\nThe catfish, known for its tender and succulent flesh, absorbs the flavors of the robust coconut sauce during the slow-cooking process. The result is a harmonious symphony of savory, spicy, and slightly sweet notes that dance on the taste buds. The dish often carries a smoky aroma, owing to the use of charred banana leaves during the cooking process.\r\n\r\nMangut Lele Mbah Marto is typically served with steamed rice, enhancing the dining experience by allowing the flavorful sauce to complement the simplicity of the rice. This culinary masterpiece not only tantalizes the palate but also offers a glimpse into the rich culinary heritage of Java, where time-honored recipes are passed down through generations. Whether enjoyed at a local eatery or prepared at home, Mangut Lele Mbah Marto is a celebration of Javanese flavors and a testament to the artistry of Indonesian gastronomy.', 'Bantul, Special Region of Yogyakarta', 'mangutlele.jpg', 'https://maps.app.goo.gl/AUn6B9StrgZFeGs8A'),
(18, 'Sate Klatak', 'Culinary', 'Sate Klatak, a culinary gem originating from Yogyakarta, Indonesia, is a savory delight that tantalizes taste buds with its unique flavors and grilling technique. This local specialty features skewers of succulent lamb or goat meat, seasoned with a blend of traditional spices, before being grilled to perfection. What sets Sate Klatak apart is the use of bicycle spokes as skewers, adding a distinctive touch to the grilling process.\r\n\r\nThe meat, tender and infused with rich, aromatic spices, takes on a smoky flavor from the open charcoal grill. Served with a side of luscious sweet soy sauce and often accompanied by fresh vegetables or rice cakes, Sate Klatak offers a harmonious blend of savory and slightly sweet notes.\r\n\r\nThe experience of indulging in Sate Klatak goes beyond the culinary; it\'s a cultural journey through the vibrant street food scene of Yogyakarta. Whether enjoyed at a roadside stall or a bustling night market, Sate Klatak is a must-try for food enthusiasts seeking an authentic taste of Indonesian cuisine with a touch of local charm.', 'Sleman, Special Region of Yogyakarta', 'sateklathak.jpeg', 'https://maps.app.goo.gl/GkXCMXyrx4nfUgVH6'),
(19, 'Gudeg Pawon', 'Culinary', 'Gudeg Pawon, a culinary delight hailing from Yogyakarta, Indonesia, is a dish that transcends flavors and cultural richness. This traditional Javanese cuisine has gained iconic status for its unique preparation and exquisite taste. Gudeg Pawon, often cooked and served from a humble roadside stall known as \"pawon\" (kitchen), presents a sensory journey through the heart of Javanese culinary heritage.\r\n\r\nAt the core of Gudeg Pawon is young jackfruit, slow-cooked in a fragrant blend of coconut milk, palm sugar, and a medley of aromatic spices. The result is a symphony of sweet and savory flavors that melt in the mouth. The dish is typically served with steamed rice, crispy chicken skin, and a dollop of creamy coconut milk, creating a harmonious combination that delights the palate.\r\n\r\nWhat sets Gudeg Pawon apart is not only its delectable taste but also the traditional cooking method, which involves using traditional clay pots and open fires, infusing the dish with a distinctive smoky aroma. Beyond its culinary excellence, Gudeg Pawon is a cultural experience, representing the rich culinary heritage of Yogyakarta and the warmth of Indonesian hospitality. This gastronomic masterpiece is a must-try for anyone seeking an authentic taste of Javanese cuisine.', 'Yogyakarta, Special Region of Yogyakarta', 'gudegpawon.jpeg', 'https://maps.app.goo.gl/dFqoewcpnMi428vw5'),
(20, 'Bakmi Jawa Pak Pele', 'Culinary', 'Bakmi Jawa Pak Pele is a culinary gem in the heart of Java, offering a delectable taste of traditional Javanese noodle cuisine. This renowned dish combines handmade noodles with a rich medley of flavorful ingredients, creating a symphony of tastes and textures that pay homage to the region\'s culinary heritage.\r\n\r\nThe star of the show is the artisanally crafted Javanese noodles, characterized by their unique texture and thickness, providing a satisfying chewiness that distinguishes them from other noodle varieties. Pak Pele\'s mastery lies not only in the noodles but also in the savory broth, which is simmered to perfection, infusing the dish with a depth of flavor.\r\n\r\nAccompanied by succulent slices of tender chicken, earthy mushrooms, and fresh vegetables, Bakmi Jawa Pak Pele offers a wholesome and hearty dining experience. The dish is often topped with aromatic fried shallots and served with a side of sambal (chili paste), allowing diners to customize the spice level according to their preferences.', 'Yogyakarta, Special Region of Yogyakarta', 'bakmijawa.jpg', 'https://maps.app.goo.gl/wqTJRGHQCWhs2jPC7'),
(21, 'Angkringan Kopi Jos', 'Culinary', 'Angkringan Kopi Jos is a culinary delight that encapsulates the rich flavors and unique cultural experience of Yogyakarta, Indonesia. This traditional Javanese street food stall is renowned for its specialty, \"Kopi Jos\" – a distinctive coffee preparation that involves adding a piece of red-hot charcoal to the coffee cup. The sizzling charcoal not only enhances the coffee\'s aroma but also imparts a unique smoky flavor, creating a memorable and robust coffee experience.\r\n\r\nLocated in the vibrant streets of Yogyakarta, Angkringan Kopi Jos exudes a charming and laid-back atmosphere. The modest stall, often adorned with colorful umbrellas and dimly lit by hanging lanterns, attracts locals and tourists alike. Beyond its signature coffee, Angkringan Kopi Jos offers an array of affordable and delectable Javanese snacks, such as nasi kucing (small portions of rice with various side dishes), bakpia (sweet pastries), and more.\r\n\r\nWhat sets this angkringan apart is not just its culinary offerings but also the communal spirit it fosters. Visitors often gather around low tables, engaged in lively conversations, creating a sense of camaraderie unique to these traditional street-side eateries. Angkringan Kopi Jos, with its distinctive coffee and delightful snacks, provides a cultural and culinary experience that captures the essence of Yogyakarta\'s rich and diverse food scene.', 'Yogyakarta, Special Region of Yogyakarta', 'angkringankopijos.jpg', 'https://maps.app.goo.gl/A8NoyvZxU5B395Fw7'),
(22, 'Soto Batok', 'Culinary', 'Soto Batok, a culinary gem in Indonesian cuisine, is a flavorful and aromatic soup that tantalizes the taste buds with its rich blend of spices and hearty ingredients. Originating from Yogyakarta, this traditional dish showcases the essence of Javanese culinary artistry. Soto Batok features a savory broth infused with a medley of spices, including turmeric, galangal, lemongrass, and lime leaves, creating a fragrant and aromatic base.\r\n\r\nWhat makes Soto Batok distinctive is the use of Batok (bamboo tubes) to serve the soup, adding a unique touch to the dining experience. The dish typically includes shredded chicken, bean sprouts, hard-boiled eggs, and rice vermicelli, creating a harmonious balance of textures and flavors.\r\n\r\nSoto Batok is often garnished with fresh herbs, lime wedges, and sambal (chili paste), allowing diners to customize the dish according to their preferences. The combination of bold spices and fresh ingredients results in a comforting and satisfying culinary experience that reflects the cultural richness of Indonesian cuisine.\r\n\r\nWhether enjoyed as a hearty breakfast or a comforting dinner, Soto Batok stands as a testament to the culinary diversity and innovation found in the heart of Indonesia, offering a warm and aromatic journey for those eager to explore the country\'s vibrant gastronomic landscape', 'Sleman, Special Region of Yogyakarta', 'sotobatok.jpg', 'https://maps.app.goo.gl/m72PqgF3s7hQ1Fbm9'),
(23, 'Mie Ayam Tumini', 'Culinary', 'Mie Ayam Tumini, a delightful Indonesian culinary gem, is a beloved dish that tantalizes the taste buds with its harmonious blend of flavors and textures. This savory noodle dish features egg noodles, known as \"mie,\" adorned with succulent, seasoned chicken slices, and bathed in a savory broth. What sets Mie Ayam Tumini apart is its rich and aromatic broth, often infused with a combination of herbs, spices, and a hint of sweetness.\r\n\r\nThe dish is typically garnished with a medley of fresh ingredients such as crisp bok choy, fragrant spring onions, and crispy fried shallots, adding layers of texture and freshness to every mouthful. The savory umami notes of the chicken complement the subtle sweetness of the broth, creating a comforting and satisfying culinary experience.\r\n\r\nMie Ayam Tumini is often customizable, allowing diners to add condiments like soy sauce, chili, or lime according to their preferences. Whether enjoyed as a quick street food fix or a heartwarming meal in a local eatery, Mie Ayam Tumini stands as a flavorful testament to Indonesia\'s rich culinary diversity, capturing the essence of comfort and taste in every bowl.', 'Yogyakarta, Special Region of Yogyakarta', 'mieayam.jpg', 'https://maps.app.goo.gl/CvapLFHLhY2eXtDa7'),
(24, 'Ayam Geprek Prektant', 'Culinary', 'Ayam Geprek \"Prektant\" is a tantalizing Indonesian culinary sensation that elevates the traditional fried chicken experience to a whole new level. This dish features succulent and crispy fried chicken, expertly seasoned to perfection. What sets Ayam Geprek apart is the \"prektant\" element, a play on words combining \"geprek\" (smashed) and \"pedas\" (spicy).\r\n\r\nThe star of the dish is the chicken, which undergoes a unique preparation process. After frying to golden perfection, the chicken is skillfully smashed and then generously coated with a fiery blend of chili, garlic, and various spices. This results in a delightful explosion of flavors with each bite – a perfect harmony of crunchiness, juiciness, and a spicy kick that tingles the taste buds.\r\n\r\nServed with a side of fragrant rice and fresh vegetables, Ayam Geprek \"Prektant\" provides a satisfying and bold culinary adventure. The combination of textures and the bold flavor profile make it a favorite among spice enthusiasts and street food aficionados alike. Whether enjoyed for lunch or dinner, Ayam Geprek \"Prektant\" promises a delightful and unforgettable gastronomic experience that showcases the rich and diverse flavors of Indonesian cuisine.', 'Sleman, Special Region of Yogyakarta', 'prektan.jpg', 'https://maps.app.goo.gl/AN4DnA4YNvVWzJXX7'),
(25, 'Kraton Yogyakarta', 'Culture', 'Kraton Yogyakarta, the royal palace of Yogyakarta in Indonesia, stands as a living testament to the rich cultural heritage of the Javanese people. Steeped in history, this majestic palace is a symbol of the sultanate\'s enduring traditions and royal legacy. Built in the mid-18th century, Kraton Yogyakarta reflects classical Javanese architecture, characterized by intricately carved wooden panels, elegant courtyards, and imposing gateways.\r\n\r\nThe Kraton is not merely a physical structure but a cultural epicenter, preserving and showcasing traditional Javanese performing arts, crafts, and rituals. Visitors can witness enchanting dance performances, intricate batik-making demonstrations, and the resonant melodies of traditional gamelan music within the palace grounds.\r\n\r\nThe palace also houses a museum displaying a vast collection of artifacts, regalia, and historical items that offer a glimpse into the lives of Yogyakarta\'s royal family. The royal court\'s adherence to Javanese customs and rituals further enriches the cultural experience, with ceremonies and events held in accordance with ancient traditions.\r\n\r\nKraton Yogyakarta stands as a captivating blend of history, art, and spirituality, inviting visitors to immerse themselves in the cultural tapestry of Java. It remains a cherished symbol of Indonesia\'s cultural resilience and the enduring legacy of Javanese royalty.', 'Yogyakarta, Special Region of Yogyakarta.', 'kraton.jpg', 'https://maps.app.goo.gl/TU58jKqdKvv7n2zy8'),
(26, 'Alun-Alun Kidul', 'Culture', 'Alun-Alun Kidul, located in the heart of Yogyakarta, Indonesia, is a vibrant town square that pulsates with cultural richness and local charm. This bustling public space is renowned for its lively atmosphere and historical significance. Flanked by majestic banyan trees, the square is a popular gathering spot for both locals and tourists.\r\n\r\nAlun-Alun Kidul is adorned with traditional Javanese architecture, offering a glimpse into the region\'s rich heritage. The central area hosts a distinctive feature known as the \"sultan\'s bathing place,\" where people believe immersing themselves in its waters brings good fortune. Visitors can also enjoy a picturesque view of Mount Merapi on the horizon.\r\n\r\nAs the sun sets, Alun-Alun Kidul transforms into a lively night market, with vibrant street food stalls and local vendors offering a myriad of traditional goods. The square becomes a hub of entertainment, featuring street performances, music, and the iconic odong-odong (colorful illuminated carts).\r\n\r\nThe southern square, known as \"Alun-Alun Kidul Selatan,\" is a space for unique activities, including the famous ritual of crossing the \"Southern Square\" barefoot, believed to bring good luck. This cultural hub not only showcases Yogyakarta\'s historical and spiritual facets but also serves as a dynamic space where tradition and modernity coalesce, making it an essential destination for those seeking an authentic Javanese experience.', 'Yogyakarta, Special Region of Yogyakarta', 'alkid.jpg', 'https://maps.app.goo.gl/p5yoRxXLAvf3kiP78'),
(27, 'Alun-Alun Utara', 'Culture', 'Alun-Alun Utara, translated as the North Square, is a bustling public space located in the heart of Yogyakarta, Indonesia. This iconic square serves as a vibrant hub for social, cultural, and recreational activities, making it a beloved gathering place for locals and tourists alike. Framed by majestic banyan trees and adorned with colorful flower beds, Alun-Alun Utara offers a picturesque setting against the backdrop of the historic Yogyakarta Palace.\r\n\r\nThe square is renowned for its distinctive feature – two massive banyan trees – where visitors can participate in a unique local tradition. It is believed that walking between these trees with one\'s eyes closed can bring good luck and prosperity.\r\n\r\nAs the sun sets, the square transforms into a lively night market, offering an array of street food, traditional snacks, and local crafts. The vibrant atmosphere, accompanied by street performers and cultural events, creates a festive ambiance that embodies the rich cultural heritage of Yogyakarta.\r\n\r\nAlun-Alun Utara is not merely a public space; it is a reflection of the city\'s spirit, where the past and present converge. From the lively daytime activities to the enchanting evening festivities, the North Square stands as a cultural nucleus, inviting visitors to immerse themselves in the dynamic tapestry of Yogyakarta\'s traditions and contemporary life.', 'Yogyakarta, Special Region of Yogyakarta', 'altar.jpg', 'https://maps.app.goo.gl/yNSKVLn94vUUADiH9'),
(28, 'Malioboro', 'Culture', 'Malioboro, located in the heart of Yogyakarta, Indonesia, is a bustling and iconic street renowned for its vibrant atmosphere and cultural significance. This bustling avenue serves as the city\'s main thoroughfare, teeming with a kaleidoscope of activities, traditional markets, and historical landmarks.\r\n\r\nLined with vibrant shops, street vendors, and traditional markets, Malioboro offers a sensory feast for visitors. The air is filled with the enticing aromas of local delicacies, while the lively chatter of locals and the melodies of traditional street performers create a lively ambiance. The street is a treasure trove of Javanese arts and crafts, offering batik textiles, traditional handicrafts, and unique souvenirs.\r\n\r\nAt the northern end of Malioboro, the grand Kraton Ngayogyakarta Hadiningrat (Sultan\'s Palace) stands as a testament to the city\'s rich history and cultural heritage. The street comes alive in the evening when the bustling activities continue, and the shops illuminate with colorful lights, creating a magical and enchanting atmosphere.\r\n\r\nMalioboro is more than a shopping destination; it is a cultural hub where the past and present coalesce, providing a glimpse into the dynamic spirit of Yogyakarta. Whether exploring historical sites, indulging in local cuisine, or shopping for unique treasures, Malioboro offers an immersive and unforgettable experience for visitors seeking the heartbeat of this vibrant Indonesian city.', 'Yogyakarta, Special Region of Yogyakarta', 'malioboro.jpg', 'https://maps.app.goo.gl/ibgdH2xUKzRKB7HQ9'),
(29, 'Titik Nol Kilometer Yogyakarta', 'Culture', 'The \"Titik Nol Kilometer Yogyakarta\" or Zero Kilometer Point in Yogyakarta, Indonesia, serves as a symbolic center and reference point for the city. Located at the heart of Yogyakarta, this landmark marks the starting point of the city\'s major roads and the point from which distances to other locations are measured.\r\n\r\nSurrounded by vibrant street vendors, cultural performances, and the hustle and bustle of daily life, the Zero Kilometer Point is not just a geographical marker but a cultural hub. Tourists and locals alike gather here to experience the lively atmosphere, purchase traditional snacks, and witness street art performances that showcase the rich Javanese culture.\r\n\r\nThe landmark itself may be a simple concrete structure, but its significance lies in its role as a meeting point for people from all walks of life. It serves as a gateway to Yogyakarta\'s cultural treasures, including the historic Kraton Yogyakarta and Malioboro Street. The Zero Kilometer Point stands as a testament to the city\'s cultural and historical importance, making it a must-visit destination for those seeking to immerse themselves in the vibrant spirit of Yogyakarta.', 'Yogyakarta, Special Region of Yogyakarta', 'titiknol.jpeg', 'https://maps.app.goo.gl/s9BQvELJWWQyggeA8'),
(30, 'Taman Sari', 'Culture', 'Taman Sari, located in Yogyakarta, Indonesia, is a cultural and historical gem that seamlessly intertwines natural beauty with architectural brilliance. Also known as the Water Castle, Taman Sari was built in the 18th century as a royal garden and pleasure complex for the Sultan of Yogyakarta.\r\n\r\nThe complex showcases exquisite Javanese architecture and design, featuring elegant pavilions, bathing pools, and lush gardens. One of its highlights is the iconic underground mosque and the bathing complex, where the sultan and his concubines once sought leisure and relaxation.\r\n\r\nThe water features, including artificial lakes and bathing pools, add a serene touch to Taman Sari\'s landscape. The picturesque ruins and remnants of the past create an enchanting atmosphere, allowing visitors to step back in time and imagine the grandeur of the royal retreat.\r\n\r\nExploring Taman Sari is a journey through both history and natural beauty. The site has become a cultural heritage destination, offering a glimpse into the opulent lifestyle of the Javanese royals. Visitors can wander through the intricate pathways, admire the architectural details, and appreciate the tranquility that pervades this historical oasis in the heart of Yogyakarta. Taman Sari stands as a testament to the rich cultural heritage of Indonesia, inviting travelers to immerse themselves in the allure of its royal past.', 'Yogyakarta, Special Region of Yogyakarta', 'tamansari.jpg', 'https://maps.app.goo.gl/cELTqb6jVBUPseLTA'),
(31, 'Benteng Vredeburg', 'Culture', 'Benteng Vredeburg, located in Yogyakarta, Indonesia, is a historical gem that unfolds the rich tapestry of Java\'s past. This colonial-era fortress, dating back to the 18th century, stands as a symbol of the city\'s cultural heritage. The architecture, a harmonious blend of Dutch and Javanese styles, reflects the complex history of the region.\r\n\r\nThe fortress, surrounded by sturdy walls and watchtowers, served as a defensive bastion during the Dutch occupation. Today, it has been repurposed into a museum that houses a remarkable collection of artifacts and exhibits. Visitors can explore the labyrinthine halls, discovering relics from Indonesia\'s struggle for independence and gaining insights into the country\'s socio-political evolution.\r\n\r\nThe museum\'s courtyards and chambers provide a serene backdrop, transporting visitors to a bygone era. The well-preserved rooms showcase period furniture, photographs, and historical documents, offering a captivating journey through time. The scenic grounds, adorned with manicured lawns and charming pathways, add to the allure of Benteng Vredeburg.\r\n\r\nBeyond its historical significance, the fortress hosts cultural events and exhibitions, making it a dynamic hub for both locals and tourists. Benteng Vredeburg stands not only as a monument to the past but also as a vibrant testament to Yogyakarta\'s commitment to preserving and sharing its rich cultural legacy.', 'Yogyakarta, Special Region of Yogyakarta', 'bentengvredeburg.jpg', 'https://maps.app.goo.gl/HTMog1p6HoqsxeZY6'),
(32, 'Prambanan Temple', 'Culture', 'Prambanan, located on the island of Java, Indonesia, is a UNESCO World Heritage Site and an iconic testament to the rich cultural and architectural heritage of the region. This majestic Hindu temple complex, built in the 9th century, stands as a masterpiece of ancient Javanese art and is dedicated to the Trimurti, the three main Hindu deities: Brahma, Vishnu, and Shiva.\r\n\r\nThe intricate design of Prambanan includes towering spires, intricately carved reliefs, and numerous shrines. The central compound, dedicated to Shiva, boasts an awe-inspiring 47-meter high main temple. Each structure is adorned with exquisite bas-reliefs, depicting episodes from Hindu epics like the Ramayana.\r\n\r\nPrambanan\'s significance extends beyond its architectural brilliance; it serves as a cultural and spiritual center, hosting various ceremonies and festivals. The temple complex also offers a serene and picturesque setting, surrounded by lush greenery and complemented by a peaceful atmosphere.\r\n\r\nAs the sun sets, Prambanan transforms into a magical landscape, with the golden hues of twilight casting a warm glow over the ancient stones. Visitors to Prambanan are not only treated to a visual feast but also a profound journey into Indonesia\'s rich history and spiritual traditions.', 'Sleman, Special Region of Yogyakarta', 'prambanan.jpg', 'https://maps.app.goo.gl/LN2CecTFia2JTgTE8'),
(33, 'Pakualaman', 'Culture', 'Pakualaman, steeped in history and cultural richness, is a regal enclave located in Yogyakarta, Indonesia. Nestled amidst lush landscapes, Pakualaman embodies the legacy of the princely state, showcasing a harmonious blend of traditional Javanese architecture and royal heritage.\r\n\r\nThe Kraton Pakualaman, the heart of this regal expanse, stands as a testament to the region\'s cultural significance. This grand palace, adorned with intricate carvings and ornate detailing, provides a glimpse into the opulent lifestyle of the Pakualaman royals. The expansive courtyards, traditional pavilions, and regal artifacts offer a captivating journey through time.\r\n\r\nSurrounding the palace, the Pakualaman area features serene gardens and sacred structures, contributing to the spiritual ambiance. Visitors can explore the historical sites, including the beautiful Masjid Agung Pakualaman, which reflects exquisite architectural mastery.\r\n\r\nPakualaman not only captivates with its architectural splendor but also serves as a cultural hub. Traditional performances, rituals, and festivals showcase the vibrant arts and traditions deeply rooted in Javanese heritage. The regal atmosphere, combined with the warmth of the local community, makes Pakualaman a must-visit destination for those seeking an immersive experience into the royal history and cultural richness of Yogyakarta.', 'Yogyakarta, Special Region of Yogyakarta', 'pakualaman.jpg', 'https://maps.app.goo.gl/dszajezJ6hV8Ng4g7'),
(34, 'Ratuboko', 'Culture', 'Ratuboko, also known as Ratu Boko or Ratu Boko Palace, is a mesmerizing archaeological site located near Yogyakarta, Indonesia. Nestled on a plateau overlooking the Prambanan Temple complex, Ratuboko offers a captivating blend of historical richness and breathtaking panoramic views. This ancient complex is believed to have been a grand royal palace, dating back to the 8th century during the Syailendra Dynasty.\r\n\r\nThe site showcases a series of impressive structures, including gateways, stone walls, and the main court, where the remnants of a once majestic palace stand. The architecture reflects a fusion of Javanese and Hindu-Buddhist influences, creating a unique and majestic ambiance.\r\n\r\nVisitors to Ratuboko can explore the various structures, intricately carved reliefs, and the expansive grounds, all while enjoying panoramic vistas of the surrounding landscapes. The site is particularly enchanting during sunset, as the golden hues cast a warm glow over the ancient stones.\r\n\r\nRatuboko serves as a testament to Indonesia\'s rich cultural and historical heritage, offering a fascinating journey through time for archaeology enthusiasts and those seeking a deeper understanding of the region\'s past. The site\'s mystical charm, combined with its archaeological significance, makes Ratuboko a must-visit destination for travelers exploring the cultural treasures of Yogyakarta.', 'Sleman, Special Region of Yogyakarta', 'ratuboko.jpg', 'https://maps.app.goo.gl/Hz8rLPhweZjrjWrW8');
INSERT INTO `destination` (`id`, `place`, `category`, `description`, `address`, `picture`, `link_maps`) VALUES
(35, 'Warungboto', 'Culture', 'Warungboto site is a cultural and historical gem nestled in Indonesia, renowned for its rich heritage and architectural significance. This site, situated in Yogyakarta, showcases a blend of Javanese and Dutch colonial influences, providing a glimpse into the region\'s diverse history. The highlight of Warungboto is the iconic Warungboto Palace, a structure that stands as a testament to Java\'s royal past.\r\n\r\nThe palace, with its intricate carvings and traditional Javanese architecture, reflects the grandeur of a bygone era. Surrounded by lush greenery and well-maintained grounds, the site offers visitors a serene environment to explore the historical remnants of Yogyakarta\'s royal legacy.\r\n\r\nBesides the palace, Warungboto site includes other structures and artifacts that contribute to the overall cultural experience. Visitors can stroll through the expansive grounds, discovering ancient relics, charming pavilions, and remnants of historical structures. The site often hosts cultural events and exhibitions, further enriching the visitor\'s understanding of the local history and traditions.\r\n\r\nWarungboto site stands as a living testament to the cultural diversity and historical richness of Yogyakarta, inviting locals and tourists alike to immerse themselves in the captivating stories and architectural wonders that define this remarkable destination.', 'Yogyakarta, Special Region of Yogyakarta', 'warungboto.jpg', 'https://maps.app.goo.gl/aoX9eXhd3YavCQfr9'),
(36, 'Panggung Krapyak', 'Culture', 'Panggung Krapyak, a cultural landmark in Indonesia, is a traditional Javanese open-air theater located in the heart of Yogyakarta. This enchanting venue is renowned for its historical significance and captivating performances that showcase the rich heritage of Javanese art and culture.\r\n\r\nNestled within the Krapyak area, the venue features an iconic open-air stage adorned with intricate Javanese architecture. The surroundings are embellished with lush greenery, creating a serene and atmospheric setting. \r\n\r\nThe traditional design of the stage reflects the deep cultural roots of the region, transporting visitors to a bygone era.\r\n\r\nPanggung Krapyak comes alive during cultural events and traditional performances, including wayang kulit (shadow puppetry), Javanese dance, and gamelan music. These performances are a mesmerizing display of Indonesia\'s artistic prowess, providing both locals and tourists with an immersive cultural experience.\r\n\r\nThe ambiance of Panggung Krapyak is further enhanced by the warm glow of traditional lamps during evening performances, adding a magical touch to the cultural showcase. Visitors can not only enjoy the performances but also appreciate the historical and architectural significance of the venue.\r\n\r\nPanggung Krapyak stands as a cultural gem, preserving and promoting the rich artistic traditions of Java. It serves as a bridge between the past and the present, allowing audiences to immerse themselves in the captivating world of Javanese performing arts.', 'Bantul, Special Region of Yogyakarta', 'panggungkrapyak.jpg', 'https://maps.app.goo.gl/MkfU5986cryVzwq66'),
(37, 'Puncak Becici', 'Nature', 'Puncak Becici, a hidden gem nestled in Indonesia, offers a mesmerizing blend of natural beauty and tranquility. Situated in a lush landscape, this scenic spot is characterized by its rolling hills, verdant valleys, and the gentle murmur of flowing rivers. The name \"Puncak Becici\" translates to \"The Peak of Charm,\" a fitting title for a place that captivates visitors with its enchanting allure.\r\n\r\nThe panoramic vistas from Puncak Becici showcase a tapestry of greenery, creating a serene backdrop against the clear blue sky. Towering trees and vibrant flora enhance the picturesque scenery, providing a haven for nature enthusiasts and those seeking respite from urban life.\r\n\r\nThe location\'s charm extends beyond its natural beauty, as visitors can explore walking trails, immerse themselves in the crisp mountain air, and appreciate the harmonious sounds of nature. Puncak Becici also serves as an ideal spot for relaxation, allowing individuals to unwind while surrounded by the calming embrace of the landscape.\r\n\r\nWhether capturing the sunrise or savoring the sunset, Puncak Becici is a haven for those who appreciate the serenity of unspoiled nature. This hidden retreat invites travelers to experience a tranquil escape, promising a rejuvenating journey amidst the captivating beauty of Indonesia\'s scenic landscapes.', 'Bantul, Special Region of Yogyakarta', 'puncakbecici.jpg', 'https://maps.app.goo.gl/iSaayKHYQETze9qC9'),
(38, 'Hutan Pinus Pengger', 'Nature', 'Hutan Pinus Pengger, located in the heart of Indonesia, is a mesmerizing pine forest that enchants visitors with its serene beauty and tranquil ambiance. The forest is a sanctuary of towering pine trees, their slender trunks reaching skyward and creating a canopy of greenery that filters sunlight, casting a gentle glow on the forest floor. The crisp scent of pine needles permeates the air, adding to the sensory experience of this natural haven.\r\n\r\nWalking through Hutan Pinus Pengger is like stepping into a fairytale landscape, with sunlight dappling the ground, creating an enchanting play of light and shadow. The forest floor is carpeted with fallen pine needles, providing a soft and inviting path for exploration.\r\n\r\nThis lush forest is not only a visual delight but also a refuge for those seeking solace in nature. The peaceful atmosphere makes it an ideal spot for picnics, meditation, or simply enjoying a quiet moment away from the hustle and bustle of city life.\r\n\r\nHutan Pinus Pengger is a popular destination for nature enthusiasts and photographers, offering a picturesque setting that changes hues with the shifting sunlight. Whether you are seeking a peaceful retreat, a family outing, or a romantic escape, Hutan Pinus Pengger promises an immersive experience in the serenity of a pine-filled paradise.', 'Bantul, Special Region of Yogyakarta', 'pinuspengger.jpg', 'https://maps.app.goo.gl/TWMY7AqnTD2wZuAy6'),
(39, 'Kalibiru', 'Nature', 'Kalibiru, nestled in the heart of Kulonprogo, Yogyakarta, is a hidden gem that unfolds as a mesmerizing blend of natural beauty and cultural charm. The highlight of Kalibiru is its stunning panoramic views, offering a breathtaking vantage point overlooking lush green landscapes and the serene Sermo Reservoir.\r\n\r\nAs a nature tourism destination, Kalibiru provides a serene escape from the hustle and bustle of urban life. Visitors can engage in a variety of outdoor activities, from exploring the elevated canopy walkways that meander through the treetops to enjoying boat rides on the tranquil reservoir. The cool, fresh air and the sounds of nature create a peaceful ambiance that soothes the soul.\r\n\r\nKalibiru is also known for its cultural touch, with the local community actively involved in preserving the area. Visitors can experience traditional Javanese hospitality through interactions with the friendly locals. Additionally, the site offers a glimpse into local agriculture and cottage industries, adding an authentic touch to the overall experience.\r\n\r\nWhether capturing the perfect sunrise or indulging in the tranquility of the surroundings, Kalibiru stands as a haven for nature enthusiasts and cultural explorers seeking a harmonious retreat in the embrace of Java\'s natural and cultural wonders.', 'Kulon Progo, Special Region of Yogyakarta', 'kalibiru.jpg', 'https://maps.app.goo.gl/EQ3VNooF5YJXCyz66'),
(40, 'Waduk Sermo', 'Nature', 'Waduk Sermo, nestled in the picturesque landscapes of Yogyakarta, Indonesia, is a captivating reservoir that serves as both a water source and a scenic recreational destination. This man-made reservoir is surrounded by lush greenery, creating a tranquil oasis away from the urban hustle. The expansive body of water, encompassed by rolling hills, offers a breathtaking panorama against the backdrop of clear skies.\r\n\r\nWaduk Sermo plays a crucial role in irrigation, providing water for agricultural purposes in the region. Beyond its utilitarian function, the reservoir has become a popular spot for outdoor enthusiasts and nature lovers. Visitors can embark on leisurely boat rides, soaking in the serene ambiance and enjoying the cool breeze.\r\n\r\nThe surrounding area is adorned with walking trails, providing opportunities for nature walks and bird watching. The calm waters reflect the verdant landscape, creating a peaceful retreat for those seeking a respite from city life. The dam itself is a marvel of engineering, and the viewpoints offer stunning vistas of the reservoir and its encompassing beauty.\r\n\r\nWaduk Sermo, with its harmonious blend of functionality and natural charm, invites visitors to unwind, connect with nature, and appreciate the intrinsic beauty of this tranquil reservoir nestled in the heart of Yogyakarta\'s captivating scenery.', 'Kulon Progo, Special Region of Yogyakarta', 'waduksermo.jpg', 'https://maps.app.goo.gl/TkCb9NUz5aasPxyS8'),
(41, 'Hutan Pinus Mangunan', 'Nature', 'Hutan Pinus Mangunan, or Mangunan Pine Forest, is a captivating natural retreat nestled in the highlands of Yogyakarta, Indonesia. This lush pine forest offers a serene escape from the hustle and bustle, presenting visitors with a tranquil haven surrounded by the beauty of nature. The forest\'s towering pine trees create a majestic canopy that casts dappled sunlight on the forest floor, providing a refreshing and cool ambiance.\r\n\r\nThe enchanting landscape of Hutan Pinus Mangunan is enhanced by well-maintained walking paths that lead visitors through the heart of the forest. These paths offer an immersive experience, allowing nature enthusiasts to explore the diverse flora and fauna that inhabit the area. The forest also provides breathtaking panoramic views of the surrounding hills and valleys, making it an ideal spot for photographers and those seeking a peaceful retreat.\r\n\r\nScattered throughout the forest are quaint wooden huts and platforms, offering a perfect place to relax and take in the scenic surroundings. Visitors can indulge in the serene atmosphere, breathe in the crisp mountain air, and appreciate the harmonious blend of pine-scented breezes and the soothing sounds of nature. Hutan Pinus Mangunan stands as a testament to the natural beauty that Indonesia has to offer, providing a refreshing escape for those seeking solace in the midst of a verdant paradise.', 'Bantul, Special Region of Yogyakarta', 'mangunan.jpg', 'https://maps.app.goo.gl/Vad83TJe5YETGw9m9'),
(42, 'Gumuk Pasir Parangkusumo', 'Nature', 'Gumuk Pasir Parangkusumo, located on the southern coast of Yogyakarta, Indonesia, is a captivating natural wonder that mesmerizes with its unique landscape. Also known as the Parangkusumo Sand Dunes, this expansive area features rolling sand hills that stretch as far as the eye can see. The fine, golden sands create a mesmerizing desert-like panorama, offering a stark contrast to the lush greenery typically associated with Indonesia.\r\n\r\nThe sand dunes of Parangkusumo provide an otherworldly experience, inviting visitors to explore their vastness on foot or through exhilarating activities like sandboarding. As the sun sets, the dunes transform into a magical canvas, bathed in the warm hues of the twilight sky. This makes it a popular destination for both adventure seekers and those looking for a serene spot to witness a breathtaking sunset over the Indian Ocean.\r\n\r\nCultural and spiritual significance adds to the allure of Gumuk Pasir Parangkusumo. Locals believe that the area holds mystical powers, and it is often visited for various traditional ceremonies and rituals. The harmonious blend of natural beauty, adventure, and cultural richness makes Gumuk Pasir Parangkusumo a must-visit destination for those seeking a unique and memorable experience on the southern coast of Java.', 'Bantul, Special Region of Yogyakarta', 'gumukpasir.jpg', 'https://maps.app.goo.gl/aNRjbC9xzurA2m4p9'),
(43, 'Goa Jomblang', 'Nature', 'Goa Jomblang, situated in the heart of Yogyakarta, Indonesia, is a natural wonder that beckons adventurers and nature enthusiasts alike. This breathtaking cave system is renowned for its vertical cave and mesmerizing \"heavenly light\" phenomenon. The journey to Goa Jomblang begins with an exciting descent through a sinkhole, revealing a surreal underground world.\r\n\r\nAs you descend into the abyss, the cave opens up to reveal towering stalactites and stalagmites, creating a cathedral-like ambiance. The highlight of the cave experience occurs when sunlight pierces through the collapsed ceiling, creating a heavenly beam of light that illuminates the cave floor. This ethereal display of nature\'s artistry is truly awe-inspiring.\r\n\r\nExplorers can witness unique geological formations, underground rivers, and a diverse ecosystem within the cave. Professional guides lead adventurers through the intricate passages, providing insights into the geological and historical significance of Goa Jomblang.\r\n\r\nThe mystical atmosphere and otherworldly beauty of Goa Jomblang make it a must-visit destination for those seeking an immersive and unforgettable adventure. The cave\'s unique geological features, combined with the enchanting play of light, create a surreal and magical experience that showcases the marvels hidden beneath the earth\'s surface.', 'Gunung Kidul, Special Region of Yogyakarta', 'goajomblang.jpg', 'https://maps.app.goo.gl/nwD1t44tt9Rz6pjU7'),
(44, 'Goa Pindul', 'Nature', 'Goa Pindul, located in Gunung Kidul, Yogyakarta, Indonesia, is a mesmerizing cave and river tubing destination that offers a unique and adventurous experience. The journey begins with a guided exploration of the mystical cave system adorned with stalactites and stalagmites, creating an otherworldly atmosphere. As you delve deeper into the underground passages, the cave opens up to a subterranean river, where the real adventure begins.\r\n\r\nVisitors embark on an exhilarating tubing expedition, drifting along the crystal-clear waters that wind through the heart of the cave. The play of light and shadows enhances the enchanting beauty of the limestone formations, creating a magical ambiance. The tubing journey continues beyond the cave\'s confines, allowing participants to bask in the natural beauty of the surrounding landscape.\r\n\r\nGoa Pindul is more than just a geological wonder; it\'s a playground for adventure seekers. The cool, refreshing waters and the thrilling tubing experience make it a perfect escapade for those seeking both excitement and natural splendor. The local guides ensure a safe and enjoyable exploration, making Goa Pindul a must-visit destination for those yearning for an unforgettable subterranean adventure in the heart of Java', 'Gunung Kidul, Special Region of Yogyakarta', 'goapindul.jpg', 'https://maps.app.goo.gl/aR6ihUnyHFSHhGQg8'),
(45, 'Mount Merapi', 'Nature', 'Mount Merapi, situated in Central Java, Indonesia, is a majestic and active stratovolcano that stands as an iconic symbol of both natural beauty and geological power. With its name translating to \"Mountain of Fire,\" Merapi has been an integral part of Indonesian history and culture. The volcano\'s towering peak, reaching approximately 2,930 meters above sea level, commands attention against the sky.\r\n\r\nThe landscape around Mount Merapi is a mix of fertile slopes and lush valleys, creating a picturesque setting that belies the potential danger beneath its surface. The mountain is revered for its spiritual significance, and numerous Javanese traditions and ceremonies are associated with its mystical presence.\r\n\r\nDespite its frequent activity, adventurous souls are drawn to Mount Merapi for its challenging hiking trails that offer breathtaking panoramic views of the surrounding landscapes. The ascent reveals diverse ecosystems, from dense forests to barren lava fields, showcasing the resilience of nature in the face of volcanic activity.\r\n\r\nMerapi\'s sporadic eruptions contribute to the formation of the surrounding landscape, shaping the region\'s geological and cultural identity. The volcano serves as a reminder of the delicate balance between the beauty and power of the natural world, making Mount Merapi a destination that captivates both thrill-seekers and those seeking to connect with Indonesia\'s rich geological and cultural heritage.', 'Sleman, Special Region of Yogyakarta', 'merapi.jpg', 'https://maps.app.goo.gl/hiXVUe8GFh2k1jm36'),
(46, 'Sri Gethuk Waterfall', 'Nature', 'Sri Gethuk Waterfall, nestled in the heart of Yogyakarta, Indonesia, is a breathtaking natural wonder that captivates with its beauty and tranquility. The waterfall is set amidst lush tropical greenery, creating a serene oasis that invites visitors to escape the hustle and bustle of urban life.\r\n\r\nThe cascading waters of Sri Gethuk create a mesmerizing spectacle as they plunge from a height, creating a fine mist that adds to the enchanting ambiance. The surrounding cliffs and rock formations add a touch of rugged elegance to the landscape, framing the waterfall like a picturesque painting.\r\n\r\nVisitors can explore the area through well-maintained pathways that wind through the verdant landscape, offering glimpses of the waterfall from various angles. The natural pool at the base of Sri Gethuk provides a refreshing opportunity for a swim, inviting travelers to cool off in the crystal-clear waters.\r\n\r\nThe site is not only a visual delight but also holds cultural significance. Visitors can learn about the local legends and folklore associated with Sri Gethuk, adding a layer of mystique to the overall experience.\r\n\r\nSri Gethuk Waterfall is a haven for nature lovers and adventure seekers, offering a perfect blend of natural beauty, cultural richness, and a peaceful retreat in the embrace of Java\'s scenic landscape.', 'Gunung Kidul, Special Region of Yogyakarta', 'srigethuk.jpg', 'https://maps.app.goo.gl/aTCi7ErqFHHE9V597'),
(47, 'Sungai Mudal', 'Nature', 'Sungai Mudal, a picturesque river nestled in the heart of Indonesia, enchants with its natural beauty and serene ambiance. This meandering watercourse winds its way through lush landscapes, creating a tranquil haven for nature enthusiasts and those seeking a peaceful escape. The riverbanks are adorned with verdant vegetation, providing a scenic backdrop to the clear waters of Sungai Mudal.\r\n\r\nA journey along Sungai Mudal unveils a landscape teeming with biodiversity. Towering trees, vibrant flora, and the soothing sounds of chirping birds contribute to the river\'s immersive natural charm. The river serves as a lifeline for local ecosystems, supporting a rich array of aquatic life and providing a habitat for diverse species.\r\n\r\nVisitors to Sungai Mudal can partake in a variety of activities, from leisurely boat rides that allow for scenic exploration to riverside picnics surrounded by the sounds of nature. The riverbanks offer idyllic spots for relaxation, where one can absorb the tranquility of the surroundings.\r\n\r\nSungai Mudal, with its untouched beauty and ecological significance, stands as a testament to Indonesia\'s rich natural heritage. Whether for nature walks, birdwatching, or simply enjoying the peaceful flow of the river, Sungai Mudal invites all to experience the rejuvenating embrace of unspoiled landscapes.', 'Kulon Progo, Special Region of Yogyakarta', 'sungaimudal.jpg', 'https://maps.app.goo.gl/QzjzA1J5pWjfY2AF7'),
(51, 'cobain', 'Culinary', '', 'coba', 'Culinary_6564975d3fd354.08440197.png', 'coba');

-- --------------------------------------------------------

--
-- Struktur dari tabel `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `role` varchar(20) NOT NULL,
  `username` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL,
  `created_at` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data untuk tabel `users`
--

INSERT INTO `users` (`id`, `role`, `username`, `password`, `created_at`) VALUES
(7, 'admin', 'admin', 'admin123', '2023-11-18 14:52:46'),
(9, 'user', 'arda', '111111', '2023-11-18 17:35:15');

--
-- Indexes for dumped tables
--

--
-- Indeks untuk tabel `destination`
--
ALTER TABLE `destination`
  ADD PRIMARY KEY (`id`);

--
-- Indeks untuk tabel `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `username` (`username`);

--
-- AUTO_INCREMENT untuk tabel yang dibuang
--

--
-- AUTO_INCREMENT untuk tabel `destination`
--
ALTER TABLE `destination`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=52;

--
-- AUTO_INCREMENT untuk tabel `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
